### PR TITLE
Expand/collapse button state sync up with manual expand/collapse icons

### LINKED ISSUE #557: Collapse/Expand All button does not update based on manual expand/collapse actions for tables
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1. Navigate to database catalog 
2. clicks on add database button and upload a database
3. click on query tab
4. Collapse all tables using either the caret or the "Collapse All" button.
5. Observe that the button changes to "Expand All".
6. Manually expand the SCHOOLS table by clicking its caret.
7. Observe that the button still reads "Collapse All" instead of updating to reflect the new state.

### Expected Result

When all tables are collapsed, the button should display "Expand All".
When all (or any) tables are expanded, the button should display "Collapse All".
The button label should always reflect the true state of the sidebar, regardless of whether it's changed via the button or manual (individual) table actions.

### Actual Results

The button text can become out of sync with the expand/collapse state if actions are performed manually rather than through the button.
This could lead to confusion about what action the button will perform.

### Additional Context

Image

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### PR DESCRIPTION
**Pull request by Vishal24-Kanini**
## Description
Fixed the issue related to synchronization of states between expand/collapse button and individual tables.

## Changes Made
- Derive a live value from the table instead of stale state.
- Now internal expand Tables is updated synchronously inside the same state update along with toggle state.
- Also make a minor change in SQLQueryEditor.tsx so the editor border should not collides with outer box

image

image

## How to Test

1. Steps to reproduce/test the behavior
2. Expected outcomes

### CODE REVIEW

File: packages/client/src/components/database/DatabaseStructureBrowser.tsx [hunk 1]
```diff
@@ -149,6 +149,9 @@ export const DatabaseStructureBrowser: React.FC<
 	onGenerateQuery,
 	generateSelectedColumnsQuery,
 }) => {
+	// trying to put "Expand All/Collapse All" button in sync with expand/collapse icons
+	const allExpanded = searchedStructure.length > 0 && searchedStructure.every((t) => !!expandedTables[t.table]);
```
Comment (Paulson-Robert) [inline packages/client/src/components/database/DatabaseStructureBrowser.tsx]: Add proper null safety and remove consoles

**Review by Paulson-Robert — CHANGES_REQUESTED** [review]

File: packages/client/src/components/database/DatabaseStructureBrowser.tsx (hunk 1 above)
Comment (Vishal24-Kanini) [reply packages/client/src/components/database/DatabaseStructureBrowser.tsx]: Yeah sure, will do that

Comment (Vishal24-Kanini) [reply packages/client/src/components/database/DatabaseStructureBrowser.tsx]: removed consoles , you can check

**Comment by Vishal24-Kanini** [comment]
@Paulson-Robert , I have re-fix the issue in the same branch and pushed changes. pls check.

**Review by Paulson-Robert — APPROVED** [review]
approved!
