### PR TITLE
Settings Design standardization

### LINKED ISSUE #2699: App Settings Revamp
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### Description

- All sections will be removed from the App Details page, except the Overview tab.
- The Settings page will be fully revamped, incorporating all required conditions.
- Navigation flow between View, Edit, and Detail pages will be analyzed and improved.
- Navigation to the Settings page from the View Details page will also be reviewed and optimized.

### Relevant Feature or Code

_No response_

### Requirements (what)

_No response_

### LINKED ISSUE #2743: DEV QA | File Explorer Icon Not Displayed Properly in File Tab – App Settings Page
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1.Login to the application.
2.Create or open an existing app.
3.Navigate to App Settings.
4.Open the File Tab.
5.Observe the File Explorer icon display.
6.Now navigate to View Details page for the same app.
7.Open the File Tab.
8.Compare the File Explorer icon display.

### Expected Result

File Explorer icon and file name should be displayed consistently and properly aligned in both App Settings and View Details File Tabs.

### Actual Results

In the App Settings → File Tab, the File Explorer icon (or name) is not displayed properly/aligned.

### Additional Context

Image

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### PR DESCRIPTION
**Pull request by KirthikaKumar-K**
## How to Test

1. Steps to reproduce/test the behavior
2. Expected outcomes

### CODE REVIEW

File: packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx [hunk 1]
```diff
@@ -0,0 +1,111 @@
+/** biome-ignore-all lint/suspicious/noExplicitAny: <explanation> */
+/** biome-ignore-all lint/suspicious/noArrayIndexKey: <explanation> */
+/** biome-ignore-all lint/correctness/noUnusedVariables: <explanation> */
```
Comment (Paulson-Robert) [inline packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx]: These 3 can't be added

File: packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+];
+
+// Similar Apps Data - removed hardcoded data
+const similarApps: any[] = [
+	// {
+	//   project_id: "1",
+	//   project_name: "Task Manager",
+	//   project_description: "Manage daily tasks efficiently",
+	// },
+];
```
Comment (Paulson-Robert) [inline packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx]: Seems like unused variables

File: packages/client/src/components/workspace/WorkspaceManager.tsx [hunk 3]
```diff
@@ -235,6 +235,146 @@ export const WorkspaceManager: React.FC<WorkspaceManagerProps> = observer(
...
+				.getBorders()
+				.forEach((border) => {
+					border.setSelected(
+						action.data.tabNode === "block-settings" &&
+							mainTabsetWeight === 0
+							? 1
+							: border.getSelected(),
+					);
+				});
+
```
Comment (Paulson-Robert) [inline packages/client/src/components/workspace/WorkspaceManager.tsx]: Need to find an optimized way to do this

**Review by Paulson-Robert — CHANGES_REQUESTED** [review]

File: packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx (hunk 1 above)
Comment (KirthikaKumar-K) [reply packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx]: resolved

File: packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx (hunk 2 above)
Comment (KirthikaKumar-K) [reply packages/client/src/pages/app/AppDetailTabs/overview-tab.tsx]: resolved

File: packages/client/src/components/workspace/WorkspaceManager.tsx (hunk 3 above)
Comment (KirthikaKumar-K) [reply packages/client/src/components/workspace/WorkspaceManager.tsx]: resolved

**Review by Paulson-Robert — APPROVED** [review]
