### PR TITLE
fix(functiontabbookmarks): function discover tab adding bookmarks

### LINKED ISSUE #1162: Function Discover tab adding bookmarks
#### How to reproduce the issue

1. Go to function page
2. Create a function
3. Make ew function discoverable
4. Log out and log in as a new user
5. Got to function page and click on Discoverable Functions tab
6. See error below
### Expected results
All discoverable functions are automatically bookmarked for users

### Actual results

Image

#### Screenshots

Please include add screenshots where applicable to help explain your problem. Please include the network tab if the issue pertains to pixel calls. 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked my terminal/console and have included relevant text here
- [ ] I have reproduced the issue with at least the latest released version.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by Gunasrini18**
## How to Test

1. Steps to reproduce/test the behavior
2. Expected outcomes

### CODE REVIEW

File: packages/client/src/pages/engine/EngineCatalogPage.tsx [hunk 1]
```diff
@@ -160,6 +160,8 @@ export const EngineCatalogPage = observer(
         const dbPixelPrefix: string =
             mode === 'Mine' ? `MyEngines` : 'MyDiscoverableEngines';
 
+        const isDiscoverable = mode !== 'Mine';
+
         const metaKeysDescription = [...metaKeys, 'description'];
 
         const getFavoritedDatabases = usePixel(`
```
Comment (johbaxter) [inline packages/client/src/pages/engine/EngineCatalogPage.tsx]: !isDiscoverable no need to make pixel call
