### PR TITLE
Fixed horizontal table scroll and Run Query button 

### LINKED ISSUE #2277: Update UI of Database Query Page
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### Description

There's a few things on the query page for a database to change: 

Image

-Change text on visualize button to "Run Query" 
-Remove cancel button 

Image

-The results in the table are scrollable, however the headers do not scroll with all the data rows, leading to them being unreadable. 

### Relevant Feature or Code

_No response_

### Requirements (what)

- [x] Change "Visualize" to "Run Query" on button text 
- [x] Remove "Cancel" button 
- [x] Make table header scrollable like rows and freeze it in place. Ex, if I scroll down, the header row should stay in place so I still can see what I'm looking at.

### PR DESCRIPTION
**Pull request by Vishal24-Kanini**
## Description
In this PR , I have update the UI of database query page. I have fixed issues related to horizontal table scroll without breaking existed vertical scroll functionality.

## Changes Made
- Removed Cancel button
- Changed "Visualize" to "Run Query"
- Make table header scrollable like rows and freeze it in place.

https://github.com/user-attachments/assets/cba16625-cee5-41af-9960-2e975b4d02ae

## How to Test

1. Steps to reproduce/test the behavior
2. Expected outcomes

### CODE REVIEW

File: packages/client/src/components/database/QueryActions.tsx [hunk 1]
```diff
@@ -49,20 +49,20 @@ export const QueryActions: React.FC<QueryActionsProps> = ({
     return (
         <StyledActions>
             <Box sx={{ display: 'flex', gap: 1 }}>
-                <Button
+                {/* <Button
```
Comment (Paulson-Robert) [inline packages/client/src/components/database/QueryActions.tsx]: Can't we remove this instead of commenting it out?

**Review by Paulson-Robert — APPROVED** [review]
Changes looks good. Approved!

File: packages/client/src/components/database/QueryActions.tsx (hunk 1 above)
Comment (Paulson-Robert) [reply packages/client/src/components/database/QueryActions.tsx]: reolved

Comment (Vishal24-Kanini) [reply packages/client/src/components/database/QueryActions.tsx]: Resolved it , please check.
