### PR TITLE
Decide on new copy/duplicate icons

### LINKED ISSUE #1390: Add success message to database export
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### Description

When downloading a database, upon clicking the Export button, the ZIP file is downloaded, but there is no toaster notification to confirm the successful download.

Download steps: 
1.	Create new database
2.	Navigate to the Database catalog Page
3.	Click on Export Button
4.	Verify file is download

### Relevant Feature or Code

Image

### Requirements (what)

- [x] Add toaster message in the top right corner in the same style of other messages within the platform 
- [x] Message should appear after the database zip has downloaded and say "Database downloaded successfully"

### LINKED ISSUE #1406: Decide on new copy/duplicate icons
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### Problem (why)

The icons for copy functions and duplicate functions are the same and/or do match throughout the platform.  We need to use different ones to distinguish these functions from each other and decide definitively what to use moving forward.  

### Impact (who)

Low code / no code users 

### Existing

Duplicate icon in blocks:

Image

Duplicate icon in layers panel: 

Image

Duplicate icon in notebook:

Image

Copy icon in variable menu: 

Image

Copy icon in notebook cell:

Image

### Requirements (what)

- [x] Decide on 1 icon for copy and 1 icon for duplicate that will be used throughout the platform 
- [x] Explore if there are any other locations besides those listed here that use the previous duplicate/copy icons

### LINKED ISSUE #1446: On Click of Delete button in the layers panel throws an error
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

Reproduced in this video

https://github.com/user-attachments/assets/86861916-df35-4458-9050-3269b40625ed

### Expected Result

on click of delete button in the layers panel the block should delete it should not throw an error

### Actual Results

on click of delete button in layer panel it throws an error

### Additional Context

_No response_

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### PR DESCRIPTION
**Pull request by NaveenRamasamy028**
**1) Introduced Distinct Icons for Copy and Duplicate Actions**
Users can now clearly differentiate between the copy and duplicate functionalities with newly assigned icons. This visual update enhances clarity and overall user experience.
**2) Success Notification Added for Database Export**
When users export files from any engine, a success message now confirms that the export has been completed successfully. This improvement applies across all supported engine types.
**3) Delete Button Error Resolved in Layer Panel**
The issue where clicking the delete button caused an error in the layer panel has been fixed. Users can now delete blocks without encountering any issues.

### CODE REVIEW

File: packages/client/src/components/engine/EngineHeader.tsx [hunk 1]
```diff
@@ -83,7 +83,24 @@ export const EngineHeader: React.FC = () => {
...
                 insightId = response.insightId;
 
-            monolithStore.download(insightId, output);
+            monolithStore
+                .download(insightId, output)
+                .then(() => {
+                    if (output && response.errors.length === 0) {
+                        notification.add({
+                            color: 'success',
+                            message: `${type} downloaded successfully`,
```
Comment (johbaxter) [inline packages/client/src/components/engine/EngineHeader.tsx]: .to(Uppercase + .toLowercase()

**Review by johbaxter — APPROVED** [review]
Looks good though ty
