### PR TITLE
fix(client): updated SocialProperty to edit, send and reset data fields

### LINKED ISSUE #641: The social.properties configuration page never sends the user data
### A clear and concise description of what the issue is.

No data the user enters is passed in the request

Image

#### How to reproduce the issue

1. Go to the settings page
2. Enter admin mode
3. Click on configuration
4. Select any authentication mode
5. Enter fields for the data
6. Click save

### Expected results

The endpoint should send the data along

### PR DESCRIPTION
**Pull request by j-arias-dev**
## Description

Updated SocialProperty state to edit, send and reset data fields. 

## Changes Made

- I removed the useForm in the SocialProperty and updated the fields to point to the state values so that we could track, edit, and submit the updated textField changes.
- Updated the reset functionality by adding a refresh functionality that calls the getLoginProperties reactor.
- Added error handling for modifyLoginProperties.

## How to Test

1. Go to the settings page
Enter admin mode
Click on configuration
Select any authentication mode
Enter value fields for the data
Click save

2. Expected outcomes
- On the network console, test to see if modifyLoginProperties returns the updated payload values
- For the reset functionality, test to see if the textField values reset to the last submitted value.

## Notes

I noticed that we have a description text field for each login property, but I don't see a description value key being returned in the getLoginProperties reactor. Should we remove the description text field?

Also, I disabled the login key text field from being edited, but let me know if we want a user to be able to also edit the login key text field as well.

### CODE REVIEW

File: packages/client/src/pages/settings/ConfigurationsPage.tsx [hunk 1]
```diff
@@ -57,37 +56,37 @@ const SOCIAL = {
...
-const StyledBox = styled(Box)(({ theme }) => ({
+const StyledBox = styled(Box)({
     padding: '0px 12px 12px 12px',
-}));
+});
 
-const StyledSearchIcon = styled(SearchOutlined)(({ theme }) => ({
-    color: '#5c5c5c',
-}));
+// const StyledSearchIcon = styled(SearchOutlined)({
```
Comment (AAfghahi) [inline packages/client/src/pages/settings/ConfigurationsPage.tsx]: Why not delete this

File: packages/client/src/pages/settings/ConfigurationsPage.tsx [hunk 2]
```diff
@@ -175,7 +174,7 @@ export const ConfigurationsPage = () => {
     const [authentication, setAuthentication] = useState(
         Object.keys(socialProps),
     );
-    const [authExpanded, setAuthExpanded] = useState(true);
+    // const [authExpanded, setAuthExpanded] = useState(true);
```
Comment (AAfghahi) [inline packages/client/src/pages/settings/ConfigurationsPage.tsx]: Is there a reason to leave this commented out

**Comment by AAfghahi** [comment]
are the reactors fully functional? The reset worked for me, but the save didn't seem to take. Is it waiting for a backend PR to merge?

**Review by AAfghahi — APPROVED** [review]
