### PR TITLE
Duplicate Block Feature not working - Bug Fix

### LINKED ISSUE #1855: Duplicate Feature is not Working while clicking the duplicate button in Drag and Drop
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1. Create a new Drag and drop app
2. Drag and Drop any Blocks 
3. Go to layers Panel or Try Duplicating by clicking any Blocks 
4. Check the issue 

### Expected Result

Block should be duplicated without any issue

### Actual Results

On click of Duplicate Button Throws error

### Additional Context

_No response_

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### LINKED ISSUE #1918: Drag and Drop any blocks throws an error in Layers panel
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1) Create a drag and drop app
2) Go to Blocks and drag and drop any blocks 
3) go to layers panel see the error

### Expected Result

Layers panel should be shown the drag and drop app

### Actual Results

Layers panel throws an error

### Additional Context

_No response_

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### PR DESCRIPTION
**Pull request by NaveenRamasamy028**
Now the user will be able to duplicate the block.

### CODE REVIEW

File: packages/client/src/components/blocks-workspace/panels/LayersPanel.tsx [hunk 1]
```diff
@@ -764,18 +764,14 @@ export const LayersPanel = observer(
...
-				const nodeIds = [id as string];
-				setSelectedLayers(nodeIds);
-
-				// Render and scroll to the new block (if your system supports it)
-				renderBlock(id as string);
-				handleMenuClose();
-			};
+			   const newId = id as string;
+			   selectLayer(selectedPages); // Refresh the layer list
+			   designer.setSelected(newId);
```
Comment (Paulson-Robert) [inline packages/client/src/components/blocks-workspace/panels/LayersPanel.tsx]: Add proper comments as we already had in the previous version

**Review by Paulson-Robert — CHANGES_REQUESTED** [review]
Add necessary comments in layers panel changes as it was already present.

File: packages/client/src/components/blocks-workspace/panels/LayersPanel.tsx (hunk 1 above)
Comment (NaveenRamasamy028) [reply packages/client/src/components/blocks-workspace/panels/LayersPanel.tsx]: Added

**Comment by NaveenRamasamy028** [comment]
> Add necessary comments in layers panel changes as it was already present.

Added

File: libs/renderer/src/store/state/state.store.ts [hunk 2]
```diff
@@ -1014,13 +1014,14 @@ export class StateStore {
 	private generateNonPageId(
 		widget: string,
 		isCommunityBlock: boolean,
+		generatedBlocks: string[],
```
Comment (Paulson-Robert) [inline libs/renderer/src/store/state/state.store.ts]: Add appropriate comment of the newly introduced param

File: libs/renderer/src/store/state/state.store.ts [hunk 3]
```diff
@@ -1407,8 +1414,9 @@ export class StateStore {
 			json = newJson;
 			variableContainer = variablesList;
 		}
+		const generatedIds = [];
```
Comment (Paulson-Robert) [inline libs/renderer/src/store/state/state.store.ts]: Rename as generatedBlockIds, to make it more understandable.

**Review by Paulson-Robert — APPROVED** [review]
Approved!

File: libs/renderer/src/store/state/state.store.ts (hunk 2 above)
Comment (NaveenRamasamy028) [reply libs/renderer/src/store/state/state.store.ts]: Added

File: libs/renderer/src/store/state/state.store.ts (hunk 3 above)
Comment (NaveenRamasamy028) [reply libs/renderer/src/store/state/state.store.ts]: Renamed
