### PR TITLE
773 chipblock linkbug

### LINKED ISSUE #773: Chip Block - Link settings bug
### A clear and concise description of what the issue is.

More information needed. 

#### How to reproduce the issue

1. 
2. 

#### Screenshots

Image

### Additional context

Ticket requested by @johbaxter from this PR: https://github.com/SEMOSS/semoss-ui/pull/751

### Requirements

What are more specific requirements that needs to take to consider this issue resolved.

- [ ]
- [ ]

### PR DESCRIPTION
**Pull request by SindhuHarika**
## Description
Implemented the navigation for link option of chip block

## Changes Made
Implemented the navigation for link option of chip block

### CODE REVIEW

File: libs/renderer/src/components/block-defaults/chip-block/ChipBlock.tsx [hunk 1]
```diff
@@ -141,7 +141,7 @@ export const ChipBlock: BlockComponent = observer(({ id }) => {
                     <a href={link}>
                         <Chip
                             {...chipProps}
-                            onClick={(e) => e.preventDefault()}
+                            onClick={(e) => {e.preventDefault();window.open(link, '_blank','noopener,noreferrer')}}
```
Comment (anurag91jain) [inline libs/renderer/src/components/block-defaults/chip-block/ChipBlock.tsx]: why does the Chip need an onClick when there is an anchor tag wrapping it? can't we get rid of the onClick on the chip altogether and use the anchor tag?

**Review by anurag91jain — CHANGES_REQUESTED** [review]

**Review by anurag91jain — APPROVED** [review]

**Comment by johbaxter** [comment]
@Mezzet link on chip fix, take a look at code
