### PR TITLE
Fix the bar chart visualization bugs

### LINKED ISSUE #2306: Trendline not displayed on Bar Chart after enabling and updating Trendline settings
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1.Create a new app.
2.Import a database into the app and run the database.
3.Navigate to the Block section.
4.Drag and drop a Bar Chart onto Page One.
5.Select the bar chart and open Block Settings.
6.Under Data, select the appropriate frame and configure the X-axis and Y-axis.
7.Navigate to Tools → Trendline.
8.Enable the Trendline toggle.
9.Click on Update Trendline.

### Expected Result

The selected trendline should be visible on the bar chart immediately after clicking Update Trendline.

### Actual Results

The trendline does not appear on the bar chart, even after enabling the toggle and updating the trendline settings.

### Additional Context

Image

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### LINKED ISSUE #2396: Title not displaying after resetting Edit X-Axis and Y-Axis Tools
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1.Open the app that have database imported
2.Navigate to the Block option
3.Drag and drop the Bar chart on page
4.Select the frame with x and y axis
5.Click on Tool
6.Open Edit X-Axis tool and modify any X-axis settings (optional).
7.Open Edit Y-Axis tool and modify any Y-axis settings (optional).
8.Click Reset for the Edit X-Axis tool.
9.Click Reset for the Edit Y-Axis tool.
10.Observe the chart after both resets are applied.

### Expected Result

The chart title should remain visible. Resetting X-Axis and Y-Axis settings should only revert axis-related properties and must not affect the chart title.

### Actual Results

The chart title disappears after resetting the Edit X-Axis and Edit Y-Axis tools.

### Additional Context

Image

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### PR DESCRIPTION
**Pull request by Gowrishankar-Palanisamy**
This PR contains the following changes 

  --> Fixed the trendline issue
  --> Fixed the deletion issue
  --> Set the data values in json 
  --> Fixed the rendering part
  --> Handled the duplication columns in X and Y axis 
  --> Updated the tooltip to display values with two digits after the decimal point

### CODE REVIEW

File: libs/renderer/src/components/block-defaults/echart-visualization-block/variant/bar-chart/Bar.tsx [hunk 1]
```diff
@@ -134,51 +134,101 @@ export const Bar = observer(({ id, updateJson }: BarProps) => {
...
+					let seriesIdx = 0;
+					seriesIdx < resultData["series"].length;
+					seriesIdx++
 				) {
-					resultData["series"][seriesIdx]["data"] =
-						frameData.data?.values?.map((item, index) => {
-							return { value: null };
-						});
+					if (
+						resultData["series"][seriesIdx] !== undefined &&
```
Comment (Paulson-Robert) [inline libs/renderer/src/components/block-defaults/echart-visualization-block/variant/bar-chart/Bar.tsx]: Using "undefined" for conditional statements is not acceptable. Need proper conditional refactor

File: packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-X-Axis.tsx [hunk 2]
```diff
@@ -70,32 +70,38 @@ const StyledTypography = styled(Typography)(({ theme }) => ({
...
+        const storedValue = initialXAxisNameRef.current;
+		
+		//Initial xaxis state used for restoring
+		const INITIAL_XAXIS_STATE = {
+			showAxis: true,
+			showAxisTitle: true,
+			xaxistitle: storedValue,
+			xaxisTitleFontSize: 12,
+			showXAxisLineTicks: false,
+			showXAxisLabels: true,
```
Comment (Paulson-Robert) [inline packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-X-Axis.tsx:96]: Why can't it be assigned directly to the state?

File: packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-Y-Axis.tsx [hunk 3]
```diff
@@ -72,33 +72,40 @@ const StyledTextField = styled(TextField)(({ theme }) => ({
...
+
+		// Use the initial value from the ref
+		const storedValue = initialXAxisNameRef.current;
+		//Initial y axis state for maintaining, restoring y axis fields
+		const INITIAL_YAXIS_STATE = {
+			showAxis: true, //yaxis show/hide
+			yaxistitle: storedValue, //y axis title value
+			showAxisTitle: true, // yaxis title hide/show
+			yaxisTitleFontSize: 12, // yaxis title fontsize
+			showYAxisLineTicks: false, // show/hide y axis ticks
```
Comment (Paulson-Robert) [inline packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-Y-Axis.tsx]: Same here

**Review by Paulson-Robert — CHANGES_REQUESTED** [review]

File: libs/renderer/src/components/block-defaults/echart-visualization-block/variant/bar-chart/Bar.tsx (hunk 1 above)
Comment (Gowrishankar-Palanisamy) [reply libs/renderer/src/components/block-defaults/echart-visualization-block/variant/bar-chart/Bar.tsx]: Refactored the code , Kindly review

File: packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-X-Axis.tsx (hunk 2 above)
Comment (Gowrishankar-Palanisamy) [reply packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-X-Axis.tsx:96]: There is a reset button , if we want to reset means I'm taking value from Initial state ,  if we directly declare in state means the state will get update , so we can't able to reset with initial values

File: packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-Y-Axis.tsx (hunk 3 above)
Comment (Gowrishankar-Palanisamy) [reply packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/bar-chart/Edit-Y-Axis.tsx]: Same functionality  like X-axis

**Review by Paulson-Robert — APPROVED** [review]
