### PR TITLE
feat(client): discoverable apps notification fixed

### LINKED ISSUE #644: [BUG] Issues with 'Discoverable apps'
#### How to reproduce the issue

1. Click on ‘Discoverable’ apps 
2. 

### Expected results

Users should be able to request for access

### Actual results

System throws an error: "Project does not exist or user does not have access to the project"

#### Screenshots

Error while requesting access
Image

### Environment

(please complete the following information):

- browser type and version:
- node.js version: `node -v`

### Tasks

- [ ]
- [ ]

### PR DESCRIPTION
**Pull request by shubham-sp-07**
## Description

The user does not have access to view this project or project id is invalid  notification msg fixed for discoverable page

## How to Test

1. Steps to reproduce/test the behavior
2. Expected outcomes

### CODE REVIEW

**Review by anurag91jain — APPROVED** [review]

**Comment by shubham-sp-07** [comment]
@CodiumAI-Agent /improve

**Comment by shubham-sp-07** [comment]
Please Refer first commit for issue fix

File: packages/client/src/pages/app/AppDetailPage.tsx [hunk 1]
```diff
@@ -239,105 +239,99 @@ export const AppDetailPage = () => {
...
+        ];
+        if (permission !== 'discoverable') {
+            promises.push(fetchDependencies(monolithStore, id));
+        }
+        const results = await Promise.allSettled(promises);
+        results.forEach((res, idx) => {
+            if (res.status === 'rejected') {
+                emitMessage(true, res.reason);
+            } else {
+                if (idx === 0) {
```
Comment (AAfghahi) [inline packages/client/src/pages/app/AppDetailPage.tsx:260]: is the array always the same way? Its never structured differently? One thing that worries me about this if else statement is that if the structure ever changes it would break. 

Is there another check that we can make that is a bit more stringent?

File: packages/client/src/pages/app/AppDetailPage.tsx [hunk 2]
```diff
@@ -239,105 +239,99 @@ export const AppDetailPage = () => {
...
+                    } else {
+                        const modelled = modelDependencies(res.value.output);
+                        setValue('dependencies', modelled);
+                        setValue('selectedDependencies', modelled);
+                    }
                 }
-            }),
-        );
+            }
+        });
```
Comment (AAfghahi) [inline packages/client/src/pages/app/AppDetailPage.tsx:334]: Could we add error checking to this as well? Does not look like we do anything if the pixel call errors out.

**Review by AAfghahi — CHANGES_REQUESTED** [review]
see comments

File: packages/client/src/pages/app/AppDetailPage.tsx (hunk 1 above)
Comment (anurag91jain) [reply packages/client/src/pages/app/AppDetailPage.tsx:260]: @AAfghahi the indexes are based on the array insertion in the promises. It will always remain the same till the array is changed

File: packages/client/src/pages/app/AppDetailPage.tsx (hunk 2 above)
Comment (anurag91jain) [reply packages/client/src/pages/app/AppDetailPage.tsx:334]: Individual calls are tracked within the indexes and if the overall call fails, that is taken as rejected.

**Review by AAfghahi — APPROVED** [review]
