### PR TITLE
fix(client): prevent search icon from overlapping app logo

### LINKED ISSUE #1793: Search Icon Overlaps with App Logo When Developer Tool Expanded
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1. Open the application.
2. Navigate to any catalog or app
3. Open the browser’s developer tools (e.g., press F12 or right-click and select “Inspect”).
4. Expand the developer tools pane by increasing its width.
5. Observe the header area: the search icon overlaps with the app logo.

### Expected Result

Search icon and app logo should not overlap

### Actual Results

Expanding the developer tools pane causes the search icon to overlap with the app logo in the header

### Additional Context

Image

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### PR DESCRIPTION
**Pull request by shubham-sp-07**
## Description
Updated navbar layout to prevent overlap between the search icon and app logo.

## Changes Made
packages/client/src/components/shared/Navbar.tsx

## How to Test
1. Navigate to the application in your browser.
2. Open Developer Tools (F12 or right-click → Inspect).
3. Toggle the device toolbar to simulate a small screen.
4. Verify that the search icon does not overlap with the app logo in the navbar.

Previous:
image

Updated:
image

### CODE REVIEW

File: packages/client/src/components/shared/Navbar.tsx [hunk 1]
```diff
@@ -26,9 +26,7 @@ const StyledNavbar = styled("div")(({ theme }) => ({
 	padding: theme.spacing(0, 4),
 }));
 
-const StyledLeft = styled(Stack)(({ theme }) => ({
-	minWidth: 0,
-}));
+const StyledLeft = styled(Stack)(({ theme }) => ({}));
```
Comment (anurag91jain) [inline packages/client/src/components/shared/Navbar.tsx]: No need of StyledLeft in this case. Change the HTML to use Stack instead of StyledLeft

**Review by anurag91jain — DISMISSED** [review]

**Review by neelneelneel — APPROVED** [review]
