### PR TITLE
feat(client): delete solo cell fix

### LINKED ISSUE #1705: Fix id/variable assign for the first cell when you delete the only cell
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1. Click delete on the top cell in a notebook and see this: 
Image

### Expected Result

The cell should have an ID still
Image

### Actual Results

_No response_

### Additional Context

_No response_

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### PR DESCRIPTION
**Pull request by Paulson-Robert**
## Description
Disabled the delete icon of the cell, if it is solo.

## Changes Made
Added additional condition to the delete disable property.
Some biome fixes

## How to Test

1. Create a notebook, it will have one cell as default.
2. Hove the cell and notice the delete icon will be disabled until that particular notebook has more than one cell.

## Notes
DEMO :  https://github.com/SEMOSS/semoss-ui/issues/1705#issuecomment-3206121420

### CODE REVIEW

**Comment by Pranchaudhari** [comment]
@Paulson-Robert Tested this issue and documented all scenarios in ticket https://github.com/SEMOSS/semoss-ui/issues/1756 . The functionality is working as expected, hence closing this from QA side.

CC :- @rameshpaulraj

File: packages/client/src/components/notebook/NotebookCell.tsx [hunk 1]
```diff
@@ -920,7 +916,7 @@ export const NotebookCell = observer(
 										{cell.isExecuted && (
```
Comment (johbaxter) [inline packages/client/src/components/notebook/NotebookCell.tsx:894]: Hey @Paulson-Robert from now on please fix inline styles on files as we go back and touch files.  Even if the work has nothing to do with your feature/bug-fix

**Review by johbaxter — APPROVED** [review]

**Comment by johbaxter** [comment]
image

@Paulson-Robert and @ehynd 

Also noticing your not fixing all the biome errors

**Comment by Paulson-Robert** [comment]
> image
> @Paulson-Robert and @ehynd
> 
> Also noticing your not fixing all the biome errors

@johbaxter , In this case I was not able to pass any other map item as key other than index. None of the map items where unique. So I forcly skiped it.
