### PR TITLE
Fix the line chart issues

### LINKED ISSUE #2500: Validate and Fix the Line Chart functionality
Validate the line chart functionality by thoroughly testing all supported configurations, data inputs, and interactions. This includes verifying rendering accuracy, axis behavior, tooltips, legends and responsiveness to different data sets. Identify and document any issues or inconsistencies observed during testing

### PR DESCRIPTION
**Pull request by Gowrishankar-Palanisamy**
This PR contains the following changes 

  --> Added the data values in json
  --> Fixed the duplicate deleting issue

### CODE REVIEW

File: libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx [hunk 1]
```diff
@@ -141,28 +141,45 @@ export const Line = observer(({ id, updateJson }: LineProps) => {
 					header.replace("Average_", ""),
 				);
 				//format the data points to match the echart specification
-				resultData["xAxis"]["data"] = valuesDataSet.map((x) => x[0]);
+				resultData["xAxis"]["data"] = valuesDataSet.map((x) => parseFloat(x[0]).toFixed(2));
```
Comment (Paulson-Robert) [inline libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx]: add proper null safe here

File: libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx [hunk 2]
```diff
@@ -141,28 +141,45 @@ export const Line = observer(({ id, updateJson }: LineProps) => {
...
+					if (!resultData["series"][index]) {
+						resultData["series"][index] = {};
+					}
+
+					resultData["series"][index]["data"] = valuesDataSet.map((x) => {
+						const value = x[index];
+						if (value === "NaN") {
+							return null; // Replace "NaN" with null
+						}
+						return parseFloat(value).toFixed(2); // Round to 2 decimal places
```
Comment (Paulson-Robert) [inline libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx]: here as well

File: packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/FrameOperations.tsx [hunk 3]
```diff
@@ -1736,34 +1736,50 @@ export const FrameOperations = observer(
...
-						],
-						dataType: [
-							...updated[key]["dataType"]?.slice(0, index),
-							...updated[key]["dataType"].slice(index + 1),
-						],
-					};
+					if (index !== -1) {
+						updated[key] = {
+							...updated[key],
+							values: updated[key]["values"].filter((_, i) => i !== index),
```
Comment (Paulson-Robert) [inline packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/FrameOperations.tsx:1763]: add type case here

**Review by Paulson-Robert — CHANGES_REQUESTED** [review]

File: libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx (hunk 1 above)
Comment (Gowrishankar-Palanisamy) [reply libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx]: Implemented the null safety

File: libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx (hunk 2 above)
Comment (Gowrishankar-Palanisamy) [reply libs/renderer/src/components/block-defaults/echart-visualization-block/variant/line-chart/Line.tsx]: Handled the null here as well

File: packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/FrameOperations.tsx (hunk 3 above)
Comment (Gowrishankar-Palanisamy) [reply packages/client/src/components/blocks-workspace/blocks/settings/custom/e-charts/variant/FrameOperations.tsx:1763]: Added the type case

**Review by Paulson-Robert — APPROVED** [review]
